from __future__ import annotations
from typing import Any, Protocol

class IConfigStore(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any): ...
    def load(self) -> dict: ...
