from __future__ import annotations
from typing import Any, Protocol

class IContextEngine(Protocol):
    def update_from_response(self, usage: dict): ...
    def should_compress(self) -> bool: ...
    def compress(self, messages: list[dict]) -> list[dict]: ...
