from __future__ import annotations
from typing import Any, Protocol

class IMemoryProvider(Protocol):
    def store(self, key: str, value: Any): ...
    def retrieve(self, key: str) -> Any | None: ...
    def search(self, query: str, limit: int = 10) -> list[dict]: ...
