from __future__ import annotations
from typing import Any, Callable, Protocol

class IToolRegistry(Protocol):
    def register(self, name: str, schema: dict, handler: Callable, **kw): ...
    def get_definitions(self, names: set[str]) -> list[dict]: ...
    def dispatch(self, name: str, args: dict) -> str: ...
    def get_all_tool_names(self) -> list[str]: ...
